### ISSUE TITLE
echo "\\1"?

### ISSUE THREAD

**Issue by jbgg** [tklauser/dash#1]
According the man pages, for echo command, "\\\\" should print '\\' character, and \0digits should print the byte in octal base.
But the command
> echo "\\\\1"

output the byte 0x01 in hexadecimal (or 001 in octal).
Is this a bad behavior or is intentional?

**Comment by tklauser** [comment]
Please not that this repository just contains a mirror of the original dash repository (where the development happens) is at git://git.kernel.org/pub/scm/utils/dash/dash.git (also see http://gondor.apana.org.au/~herbert/dash/).

From a quick look I'd say this is intended behavior, but you might want to report your concern on the dash mailing list: dash@vger.kernel.org.

Hope that helps.
